version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./:/usr/local/app
    ports:
      - 4000:8001
    env_file: .env
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      - postgres
    restart: always

  postgres:
    platform: linux/amd64
    image: postgres
    container_name: phishing_db
    environment:
      - POSTGRES_PASSWORD=naijason
      - POSTGRES_DB=postgres
    # volumes:
    #   - postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-db:


